# Example pytest-bdd step definitions — generated by /speckit.bdd.scaffold
# Replace each `raise NotImplementedError` with your actual implementation.

import pytest
from pytest_bdd import scenarios, given, when, then, parsers

scenarios("../../features/")


@pytest.fixture
def context():
    return {}


@given("the application is running")
def application_is_running(app_client):
    # TODO: Confirm the app is reachable; app_client fixture should set up a test HTTP client
    raise NotImplementedError("Implement: ensure app is running")


@given(parsers.parse('a user account exists with email "{email}" and password "{password}"'))
def existing_user(db, email, password):
    # TODO: Use the db fixture to INSERT a user row with a hashed password
    raise NotImplementedError("Implement: seed user in test database")


@given(parsers.parse('the user has failed to log in {count:d} times consecutively with email "{email}"'))
def user_has_failed_logins(db, count, email):
    # TODO: Insert `count` failed login attempt records for this email in the DB
    raise NotImplementedError("Implement: seed failed login records")


@when(parsers.parse('the user submits login with email "{email}" and password "{password}"'))
def user_submits_login(app_client, email, password, context):
    # TODO: POST /auth/login with {"email": email, "password": password}
    # Store the response: context["response"] = app_client.post("/auth/login", json={...})
    raise NotImplementedError("Implement: POST to /auth/login")


@when(parsers.parse('the user attempts to register with email "{email}" and password "{password}"'))
def user_attempts_registration(app_client, email, password, context):
    # TODO: POST /auth/register with the given credentials
    raise NotImplementedError("Implement: POST to /auth/register")


@then("the user is redirected to the dashboard")
def user_redirected_to_dashboard(context):
    # TODO: Assert context["response"].status_code == 302
    # Assert context["response"].headers["Location"] == "/dashboard"
    raise NotImplementedError("Implement: check redirect response")


@then("a session token is issued")
def session_token_issued(context):
    # TODO: Assert "token" in context["response"].json()
    raise NotImplementedError("Implement: verify token in response")


@then("no session token is issued")
def no_session_token_issued(context):
    # TODO: Assert "token" not in context["response"].json()
    raise NotImplementedError("Implement: verify no token in error response")


@then(parsers.parse('the error message "{message}" is displayed'))
def error_message_displayed(message, context):
    # TODO: Assert context["response"].json()["error"] == message
    raise NotImplementedError("Implement: check error message in response body")


@then("the account is locked for 15 minutes")
def account_is_locked(db, context):
    # TODO: Query the DB and assert the user's locked_until timestamp is ~15 minutes from now
    raise NotImplementedError("Implement: verify account lock in database")
